export const chiefComplaintOptions = [
  { value: "Abdominal Pain", label: "Abdominal Pain" },
  { value: "Ankle Pain", label: "Ankle Pain" },
  { value: "Anxiety", label: "Anxiety" },
  { value: "Arm Pain", label: "Arm Pain" },
  { value: "Back Pain", label: "Back Pain" },
  { value: "Chest Pain", label: "Chest Pain" },
  { value: "Chronic Cough", label: "Chronic Cough" },
  { value: "Chronic Fatigue", label: "Chronic Fatigue" },
  { value: "Chronic Headache", label: "Chronic Headache" },
  { value: "Chronic Pain", label: "Chronic Pain" },
  { value: "Confusion", label: "Confusion" },
  { value: "Constipation", label: "Constipation" },
  { value: "Dental Pain", label: "Dental Pain" },
  { value: "Depression", label: "Depression" },
  { value: "Diarrhea", label: "Diarrhea" },
  { value: "Difficulty Breathing", label: "Difficulty Breathing" },
  { value: "Difficulty Swallowing", label: "Difficulty Swallowing" },
  { value: "Dizziness/Vertigo", label: "Dizziness/Vertigo" },
  { value: "Ear Pain", label: "Ear Pain" },
  { value: "Elbow Pain", label: "Elbow Pain" },
  { value: "Eye Irritation", label: "Eye Irritation" },
  { value: "Facial Pain", label: "Facial Pain" },
  { value: "Fainting", label: "Fainting" },
  { value: "Fever", label: "Fever" },
  { value: "Foot Pain", label: "Foot Pain" },
  { value: "Genital Itching", label: "Genital Itching" },
  { value: "Genital Pain", label: "Genital Pain" },
  { value: "Hand Pain", label: "Hand Pain" },
  { value: "Headache", label: "Headache" },
  { value: "Hearing Loss", label: "Hearing Loss" },
  { value: "Hip Pain", label: "Hip Pain" },
  { value: "Insomnia", label: "Insomnia" },
  { value: "Irregular Heartbeat", label: "Irregular Heartbeat" },
  { value: "Itchy Skin", label: "Itchy Skin" },
  { value: "Joint Stiffness", label: "Joint Stiffness" },
  { value: "Knee Pain", label: "Knee Pain" },
  { value: "Loss of Appetite", label: "Loss of Appetite" },
  { value: "Loss of Balance", label: "Loss of Balance" },
  { value: "Memory Loss", label: "Memory Loss" },
  { value: "Mood Changes", label: "Mood Changes" },
  { value: "Muscle Cramps", label: "Muscle Cramps" },
  { value: "Muscle Weakness", label: "Muscle Weakness" },
  { value: "Nasal Congestion", label: "Nasal Congestion" },
  { value: "Nausea/Vomiting", label: "Nausea/Vomiting" },
  { value: "Neck Pain", label: "Neck Pain" },
  { value: "Nerve Pain", label: "Nerve Pain" },
  { value: "Numbness/Tingling", label: "Numbness/Tingling" },
  { value: "Pelvic Pain", label: "Pelvic Pain" },
  { value: "Rash", label: "Rash" },
  { value: "Shortness of Breath", label: "Shortness of Breath" },
  { value: "Shoulder Pain", label: "Shoulder Pain" },
  { value: "Sinus Pressure", label: "Sinus Pressure" },
  { value: "Skin Lesions", label: "Skin Lesions" },
  { value: "Sleep Disturbances", label: "Sleep Disturbances" },
  { value: "Sneezing", label: "Sneezing" },
  { value: "Sore Throat", label: "Sore Throat" },
  { value: "Stress", label: "Stress" },
  { value: "Swelling", label: "Swelling" },
  { value: "Swollen Lymph Nodes", label: "Swollen Lymph Nodes" },
  { value: "Tinnitus (Ringing in Ears)", label: "Tinnitus (Ringing in Ears)" },
  { value: "Tooth Pain", label: "Tooth Pain" },
  { value: "Tremors", label: "Tremors" },
  { value: "Urinary Incontinence", label: "Urinary Incontinence" },
  {
    value: "Urinary Tract Infection Symptoms",
    label: "Urinary Tract Infection Symptoms",
  },
  { value: "Vaginal Discharge", label: "Vaginal Discharge" },
  { value: "Vision Changes", label: "Vision Changes" },
  { value: "Weakness", label: "Weakness" },
  { value: "Weight Gain", label: "Weight Gain" },
  { value: "Weight Loss", label: "Weight Loss" },
  { value: "Wheezing", label: "Wheezing" },
  { value: "Wrist Pain", label: "Wrist Pain" },
];
