export const Routeoptions = [
  { value: "Oral", label: "Oral" },
  { value: "Topical", label: "Topical" },
  { value: "Inhalation", label: "Inhalation" },
  { value: "Nasal", label: "Nasal" },
  { value: "Ophthalmic", label: "Ophthalmic" },
  { value: "Otic", label: "Otic" },
  { value: "Rectal", label: "Rectal" },
  { value: "Parenteral", label: "Parenteral" },
  { value: "Sublingual", label: "Sublingual" },
  { value: "Transdermal", label: "Transdermal" },
];
export const frequencyoptions = [
  { value: "QD", label: "QD" },
  { value: "BID", label: "BID" },
  { value: "TID", label: "TID" },
  { value: "QID", label: "QID" },
  { value: "QH", label: "QH" },
  { value: "Q2H", label: "Q2H" },
  { value: "Q4H", label: "Q4H" },
  { value: "Q6H", label: "Q6H" },
  { value: "Q12H", label: "Q12H" },
];

export const ExternalMedicationOptions = [
  { drugname: "Acetaminophen", value: "Acetaminophen", label: "Acetaminophen" },
  { drugname: "Amoxicillin", value: "Amoxicillin", label: "Amoxicillin" },
  { drugname: "Atorvastatin", value: "Atorvastatin", label: "Atorvastatin" },
  { drugname: "Azithromycin", value: "Azithromycin", label: "Azithromycin" },
  { drugname: "Ciprofloxacin", value: "Ciprofloxacin", label: "Ciprofloxacin" },
  { drugname: "Citalopram", value: "Citalopram", label: "Citalopram" },
  { drugname: "Clonazepam", value: "Clonazepam", label: "Clonazepam" },
  { drugname: "Codeine", value: "Codeine", label: "Codeine" },
  { drugname: "Diazepam", value: "Diazepam", label: "Diazepam" },
  { drugname: "Digoxin", value: "Digoxin", label: "Digoxin" },
  { drugname: "Fluoxetine", value: "Fluoxetine", label: "Fluoxetine" },
  { drugname: "Gabapentin", value: "Gabapentin", label: "Gabapentin" },
  {
    drugname: "Hydrochlorothiazide",
    value: "Hydrochlorothiazide",
    label: "Hydrochlorothiazide",
  },
  { drugname: "Ibuprofen", value: "Ibuprofen", label: "Ibuprofen" },
  { drugname: "Levothyroxine", value: "Levothyroxine", label: "Levothyroxine" },
  { drugname: "Lisinopril", value: "Lisinopril", label: "Lisinopril" },
  { drugname: "Lorazepam", value: "Lorazepam", label: "Lorazepam" },
  { drugname: "Losartan", value: "Losartan", label: "Losartan" },
  { drugname: "Metformin", value: "Metformin", label: "Metformin" },
  { drugname: "Metoprolol", value: "Metoprolol", label: "Metoprolol" },
  { drugname: "Omeprazole", value: "Omeprazole", label: "Omeprazole" },
  { drugname: "Paracetamol", value: "Paracetamol", label: "Paracetamol" },
  { drugname: "Prednisone", value: "Prednisone", label: "Prednisone" },
  { drugname: "Sertraline", value: "Sertraline", label: "Sertraline" },
  { drugname: "Simvastatin", value: "Simvastatin", label: "Simvastatin" },
  { drugname: "Tamsulosin", value: "Tamsulosin", label: "Tamsulosin" },
  { drugname: "Tramadol", value: "Tramadol", label: "Tramadol" },
  { drugname: "Warfarin", value: "Warfarin", label: "Warfarin" },
  { drugname: "Alprazolam", value: "Alprazolam", label: "Alprazolam" },
  { drugname: "Amlodipine", value: "Amlodipine", label: "Amlodipine" },
  { drugname: "Atenolol", value: "Atenolol", label: "Atenolol" },
  { drugname: "Bupropion", value: "Bupropion", label: "Bupropion" },
  { drugname: "Carvedilol", value: "Carvedilol", label: "Carvedilol" },
  { drugname: "Clindamycin", value: "Clindamycin", label: "Clindamycin" },
  { drugname: "Diclofenac", value: "Diclofenac", label: "Diclofenac" },
  // Add more medication objects as needed
];
