export const medicalLabTestsOptions = [
  {
    value: "activated-partial-thromboplastin-time",
    label: "Activated Partial Thromboplastin Time (aPTT)",
  },
  { value: "anti-centromere-antibody", label: "Anti-Centromere Antibody" },
  {
    value: "anti-double-stranded-dna-antibody",
    label: "Anti-Double Stranded DNA Antibody",
  },
  { value: "anti-jo-1-antibody", label: "Anti-Jo-1 Antibody" },
  {
    value: "anti-ribonucleoprotein-antibody",
    label: "Anti-Ribonucleoprotein Antibody",
  },
  { value: "anti-scl-70-antibody", label: "Anti-Scl-70 Antibody" },
  { value: "anti-ssb-la-antibody", label: "Anti-SSB (La) Antibody" },
  { value: "anti-ssa-ro-antibody", label: "Anti-SSA (Ro) Antibody" },
  { value: "anti-smith-antibody", label: "Anti-Smith Antibody" },
  {
    value: "anti-thyroglobulin-antibody",
    label: "Anti-Thyroglobulin Antibody",
  },
  {
    value: "anti-thyroid-stimulating-hormone-receptor-antibody",
    label: "Anti-Thyroid Stimulating Hormone Receptor Antibody",
  },
  { value: "antinuclear-antibody", label: "Antinuclear Antibody (ANA)" },
  { value: "antisperm-antibody", label: "Antisperm Antibody" },
  { value: "basic-metabolic-panel", label: "Basic Metabolic Panel (BMP)" },
  { value: "blood-culture", label: "Blood Culture" },
  { value: "bicarbonate", label: "Bicarbonate" },
  { value: "breast-cancer-antigen", label: "Breast Cancer Antigen (CA 15-3)" },
  { value: "bun", label: "BUN (Blood Urea Nitrogen)" },
  { value: "calcium", label: "Calcium" },
  { value: "cardio-bnp", label: "Cardiac BNP" },
  { value: "cardio-ck-mb", label: "Cardiac CK-MB" },
  { value: "cardio-d-dimer", label: "Cardiac D-Dimer" },
  { value: "cardio-myoglobin", label: "Cardiac Myoglobin" },
  { value: "cardio-troponin", label: "Cardiac Troponin" },
  {
    value: "carcinoembryonic-antigen",
    label: "Carcinoembryonic Antigen (CEA)",
  },
  { value: "celiac-disease-panel", label: "Celiac Disease Panel" },
  { value: "chloride", label: "Chloride" },
  { value: "complete-blood-count", label: "Complete Blood Count (CBC)" },
  {
    value: "comprehensive-metabolic-panel",
    label: "Comprehensive Metabolic Panel (CMP)",
  },
  { value: "cortisol", label: "Cortisol" },
  { value: "covid-19", label: "COVID-19" },
  { value: "c-peptide", label: "C-Peptide" },
  { value: "c-reactive-protein", label: "C-Reactive Protein (CRP)" },
  { value: "creatinine", label: "Creatinine" },
  { value: "crp", label: "CRP (C-Reactive Protein)" },
  {
    value: "cyclic-citrullinated-peptide-antibody",
    label: "Cyclic Citrullinated Peptide (CCP) Antibody",
  },
  { value: "d-dimer", label: "D-Dimer" },
  { value: "electrolyte-panel", label: "Electrolyte Panel" },
  {
    value: "erythrocyte-sedimentation-rate",
    label: "Erythrocyte Sedimentation Rate (ESR)",
  },
  { value: "estradiol", label: "Estradiol" },
  { value: "folate", label: "Folate" },
  {
    value: "follicle-stimulating-hormone",
    label: "Follicle-Stimulating Hormone (FSH)",
  },
  { value: "free-t3", label: "Free T3" },
  { value: "free-t4", label: "Free T4" },
  { value: "fructosamine", label: "Fructosamine" },
  { value: "gfr", label: "GFR (Glomerular Filtration Rate)" },
  { value: "glucose", label: "Glucose" },
  { value: "glucose-tolerance", label: "Glucose Tolerance" },
  { value: "hba1c", label: "HbA1c (Glycated Hemoglobin)" },
  { value: "hepatitis-b", label: "Hepatitis B" },
  { value: "hepatitis-c", label: "Hepatitis C" },
  { value: "hepatitis-panel", label: "Hepatitis Panel" },
  {
    value: "hcg-pregnancy",
    label: "HCG (Human Chorionic Gonadotropin) Pregnancy",
  },
  { value: "hemoglobin-a1c", label: "Hemoglobin A1C" },
  { value: "hiv", label: "HIV (Human Immunodeficiency Virus)" },
  { value: "h-pylori", label: "H. Pylori" },
  { value: "h-pylori-antibody", label: "H. Pylori Antibody" },
  { value: "immunoglobulin", label: "Immunoglobulin (Ig)" },
  { value: "influenza", label: "Influenza" },
  { value: "insulin", label: "Insulin" },
  { value: "iron-panel", label: "Iron Panel" },
  { value: "kidney-function", label: "Kidney Function" },
  { value: "lipid-panel", label: "Lipid Panel" },
  { value: "liver-function", label: "Liver Function (LFT)" },
  { value: "luteinizing-hormone", label: "Luteinizing Hormone (LH)" },
  { value: "lyme-antibody", label: "Lyme Antibody" },
  { value: "lyme-disease", label: "Lyme Disease" },
  { value: "magnesium", label: "Magnesium" },
  { value: "mononucleosis", label: "Mononucleosis" },
  { value: "monospot", label: "Monospot" },
  { value: "ovarian-cancer-antigen", label: "Ovarian Cancer Antigen (CA 125)" },
  { value: "phosphorus", label: "Phosphorus" },
  { value: "potassium", label: "Potassium" },
  { value: "progesterone", label: "Progesterone" },
  { value: "prolactin", label: "Prolactin" },
  {
    value: "prostate-specific-antigen",
    label: "Prostate-Specific Antigen (PSA)",
  },
  { value: "prothrombin-time", label: "Prothrombin Time (PT)" },
  { value: "rheumatoid-factor", label: "Rheumatoid Factor" },
  {
    value: "respiratory-syncytial-virus",
    label: "Respiratory Syncytial Virus (RSV)",
  },
  { value: "reproductive-hormone-panel", label: "Reproductive Hormone Panel" },
  { value: "sodium", label: "Sodium" },
  { value: "sperm-count", label: "Sperm Count" },
  { value: "sperm-morphology", label: "Sperm Morphology" },
  { value: "sperm-motility", label: "Sperm Motility" },
  { value: "stool-calprotectin", label: "Stool Calprotectin" },
  {
    value: "stool-clostridium-difficile",
    label: "Stool Clostridium difficile",
  },
  { value: "stool-culture", label: "Stool Culture" },
  { value: "stool-elastase", label: "Stool Elastase" },
  { value: "stool-fat", label: "Stool Fat" },
  { value: "stool-lactoferrin", label: "Stool Lactoferrin" },
  { value: "stool-occult-blood", label: "Stool Occult Blood" },
  { value: "stool-ova-and-parasites", label: "Stool Ova and Parasites" },
  { value: "testosterone", label: "Testosterone" },
  { value: "thyroglobulin", label: "Thyroglobulin" },
  {
    value: "thyroid-peroxidase-antibody",
    label: "Thyroid Peroxidase Antibody",
  },
  {
    value: "thyroid-stimulating-hormone",
    label: "Thyroid Stimulating Hormone (TSH)",
  },
  { value: "thyroxine", label: "Thyroxine (T4)" },
  { value: "triiodothyronine", label: "Triiodothyronine (T3)" },
  { value: "uric-acid", label: "Uric Acid" },
  { value: "urinalysis", label: "Urinalysis" },
  { value: "urine-albumin", label: "Urine Albumin" },
  { value: "urine-bilirubin", label: "Urine Bilirubin" },
  { value: "urine-color-and-appearance", label: "Urine Color and Appearance" },
  { value: "urine-creatinine", label: "Urine Creatinine" },
  { value: "urine-glucose", label: "Urine Glucose" },
  { value: "urine-ketones", label: "Urine Ketones" },
  { value: "urine-leukocyte-esterase", label: "Urine Leukocyte Esterase" },
  { value: "urine-microalbumin", label: "Urine Microalbumin" },
  { value: "urine-nitrite", label: "Urine Nitrite" },
  { value: "urine-osmolality", label: "Urine Osmolality" },
  { value: "urine-ph", label: "Urine pH" },
  { value: "urine-protein", label: "Urine Protein" },
  { value: "urine-specific-gravity", label: "Urine Specific Gravity" },
  { value: "urine-urobilinogen", label: "Urine Urobilinogen" },
  { value: "vitamin-b12", label: "Vitamin B12" },
  { value: "vitamin-d", label: "Vitamin D" },
];
